from __future__ import annotations

from pathlib import Path
from typing import Iterable


def build_html_page(title: str, sections: Iterable[str]) -> str:
    body = "\n".join(sections)
    return f"""<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
  <title>{title}</title>
  <style>
    :root {{
      --bg: #f6f7fb;
      --ink: #1f2937;
      --muted: #4b5563;
      --card: #ffffff;
      --accent: #0f766e;
      --border: #d1d5db;
    }}
    body {{ margin: 0; font-family: "Segoe UI", sans-serif; background: var(--bg); color: var(--ink); }}
    .wrap {{ max-width: 1200px; margin: 0 auto; padding: 24px; }}
    h1 {{ margin-top: 0; }}
    .meta {{ color: var(--muted); margin-bottom: 18px; }}
    .card {{ background: var(--card); border: 1px solid var(--border); border-radius: 12px; padding: 16px; margin-bottom: 16px; }}
    a {{ color: var(--accent); }}
    table {{ border-collapse: collapse; width: 100%; }}
    th, td {{ border: 1px solid var(--border); padding: 6px 8px; text-align: left; }}
  </style>
</head>
<body>
  <div class=\"wrap\">
    <h1>{title}</h1>
    <div class=\"meta\">Generated by Codex Data Pipeline</div>
    {body}
  </div>
</body>
</html>
"""


def save_html(path: Path, html: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding="utf-8")
    return path
